# SPDX-FileCopyrightText: 2024 Machine Builder AG
#
# SPDX-License-Identifier: MIT
---
project_name: dummy-asset-link

version: 2

before:
  hooks:
    - go generate ./...
    - go mod vendor

builds:
  - id: dummy-asset-link
    binary: dummy-asset-link
    tags:
      - webserver
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags '-static'

      - -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}}

    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - formats: [ 'tar.gz' ]
    files:
      - vendor\
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]



nfpms:
  - id: dummy-asset-link
    package_name: dummy-asset-link
    ids:
      - dummy-asset-link
    vendor: Machine Builder AG
    homepage: https://www.device-builder.local
    maintainer: David Device Builder <david@david-builder.local>
    description: |-
      Dummy Asset Link
    license: Machine Builder AG 2024
    formats:
      - deb
    bindir: /usr/bin
    version_metadata: git
    section: default
    priority: extra
    contents:
      - src: contrib/dummy-asset-link.service
        dst: /lib/systemd/system/dummy-asset-link.service
        type: "config"
    scripts:
      postinstall: "contrib/postinstall.bash"
      postremove: "contrib/postremove.bash"


checksum:
  name_template: "{{.ProjectName}}_{{.Version}}.sha256"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"
  

dockers:
  - id: dummy-asset-link-linux-amd64
    ids:
      - dummy-asset-link
    image_templates:
      - "dummy-asset-link:{{ .Tag }}-linux-amd64"
      - "dummy-asset-link:latest-linux-amd64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
  - id: dummy-asset-link-arm64
    ids:
      - dummy-asset-link
    image_templates:
      - "dummy-asset-link:{{ .Tag }}-linux-arm64"
      - "dummy-asset-link:latest-linux-arm64"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64

docker_manifests:
  - name_template: "dummy-asset-link:{{ .Tag }}"
    image_templates:
      - "dummy-asset-link:{{ .Tag }}-linux-amd64"
      - "dummy-asset-link:{{ .Tag }}-linux-arm64"
  - name_template: "dummy-asset-link:latest"
    image_templates:
      - "dummy-asset-link:latest-linux-amd64"
      - "dummy-asset-link:latest-linux-arm64"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
